version: "3.9"
services:
  simc:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["/app/SimulationCraft/simc", "./run.simc"]
    volumes:
      - type: bind
        source: ./volume
        target: /app/SimulationCraft/results
